export const GET_PROPOSED_MATCH = 'GET_PROPOSED_MATCH'; 
export const APPROVE_PROPOSED_MATCH = 'APPROVE_PROPOSED_MATCH'; 
export const PROPOSE_MATCH   ='PROPOSE_MATCH'
         
export const PROPOSED_MATCH_TO_CONFIRM = 'PROPOSED_MATCH_TO_CONFIRM'


export const TEST   ='TEST'