export const GET_TAC_WETH_PAIR = 'GET_TAC_WETH_PAIR'; 
export const  UPDATE_TAC_WETH_PAIR = 'UPDATE_TAC_WETH_PAIR'
export const GET_WALLET_BALANCE = 'GET_WALLET_BALANCE'
export const UPDATE_WALLET_BALANCE = 'UPDATE_WALLET_BALANCE'